## This configuration was generated by terraform-provider-oci

resource oci_containerengine_cluster export_cluster1 {
  compartment_id = var.compartment_ocid
  endpoint_config {
    is_public_ip_enabled = "true"
    nsg_ids = [
    ]
    subnet_id = oci_core_subnet.export_oke-k8sendpoint-subnet-quick-cluster1-cfcc03f15-regional.id
  }
  image_policy_config {
    is_policy_enabled = "false"
  }
  #kms_key_id = <<Optional value not found in discovery>>
  kubernetes_version = "v1.19.7"
  name               = "cluster1"
  options {
    add_ons {
      is_kubernetes_dashboard_enabled = "false"
      is_tiller_enabled               = "false"
    }
    admission_controller_options {
      is_pod_security_policy_enabled = "false"
    }
    kubernetes_network_config {
      pods_cidr     = "10.244.0.0/16"
      services_cidr = "10.96.0.0/16"
    }
    service_lb_subnet_ids = [
      oci_core_subnet.export_oke-svclbsubnet-quick-cluster1-cfcc03f15-regional.id,
    ]
  }
  vcn_id = oci_core_vcn.export_oke-vcn-quick-cluster1-cfcc03f15.id
}

resource oci_containerengine_node_pool export_pool1 {
  cluster_id     = oci_containerengine_cluster.export_cluster1.id
  compartment_id = var.compartment_ocid
  initial_node_labels {
    key   = "name"
    value = "pool1"
  }
  kubernetes_version = "v1.19.7"
  name               = "pool1"
  node_config_details {
    placement_configs {
      availability_domain = "EAYH:EU-FRANKFURT-1-AD-1"
      subnet_id           = oci_core_subnet.export_oke-nodesubnet-quick-cluster1-cfcc03f15-regional.id
    }
    placement_configs {
      availability_domain = "EAYH:EU-FRANKFURT-1-AD-3"
      subnet_id           = oci_core_subnet.export_oke-nodesubnet-quick-cluster1-cfcc03f15-regional.id
    }
    placement_configs {
      availability_domain = "EAYH:EU-FRANKFURT-1-AD-2"
      subnet_id           = oci_core_subnet.export_oke-nodesubnet-quick-cluster1-cfcc03f15-regional.id
    }
    size = "3"
  }
  node_metadata = {
  }
  node_shape = "VM.Standard.B1.1"
  node_source_details {
    #boot_volume_size_in_gbs = <<Optional value not found in discovery>>
    image_id    = "ocid1.image.oc1.eu-frankfurt-1.aaaaaaaa62zux7w2njw7yyhjcwydpuzhbi2iavnhm4lwbruthl6b5htjlkyq"
    source_type = "IMAGE"
  }
  #quantity_per_subnet = <<Optional value not found in discovery>>
  ssh_public_key = ""
  #subnet_ids = <<Optional value not found in discovery>>
}

