## This configuration was generated by terraform-provider-oci

resource oci_core_internet_gateway export_oke-igw-quick-cluster1-cfcc03f15 {
  compartment_id = var.compartment_ocid
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "oracleidentitycloudservice/mika.rinne@oracle.com"
    "Oracle-Tags.CreatedOn" = "2021-04-16T08:05:10.916Z"
  }
  display_name = "oke-igw-quick-cluster1-cfcc03f15"
  enabled      = "true"
  freeform_tags = {
  }
  vcn_id = oci_core_vcn.export_oke-vcn-quick-cluster1-cfcc03f15.id
}

resource oci_core_public_ip export_Floating-Public-IP-for-cluster-ocid1-cluster-oc1-eu-frankfurt-1-aaaaaaaaei3jyn3j7tdszrqul2uevgiq4l46tm7wulzejkc37cuuo76edvoa {
  compartment_id = var.compartment_ocid
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "oracleidentitycloudservice/mika.rinne@oracle.com"
    "Oracle-Tags.CreatedOn" = "2021-04-16T08:05:29.274Z"
  }
  display_name = "Floating Public IP for cluster ocid1.cluster.oc1.eu-frankfurt-1.aaaaaaaaei3jyn3j7tdszrqul2uevgiq4l46tm7wulzejkc37cuuo76edvoa"
  freeform_tags = {
  }
  lifetime      = "RESERVED"
  private_ip_id = oci_core_private_ip.export_Service-VNIC-for-cluster-ocid1-cluster-oc1-eu-frankfurt-1-aaaaaaaaei3jyn3j7tdszrqul2uevgiq4l46tm7wulzejkc37cuuo76edvoa.id
  #public_ip_pool_id = <<Optional value not found in discovery>>
}

resource oci_core_service_gateway export_oke-igw-quick-cluster1-cfcc03f15_1 {
  compartment_id = var.compartment_ocid
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "oracleidentitycloudservice/mika.rinne@oracle.com"
    "Oracle-Tags.CreatedOn" = "2021-04-16T08:05:12.996Z"
  }
  display_name = "oke-igw-quick-cluster1-cfcc03f15"
  freeform_tags = {
  }
  #route_table_id = <<Optional value not found in discovery>>
  services {
    service_id = "ocid1.service.oc1.eu-frankfurt-1.aaaaaaaa7ncsqkj6lkz36dehifizupyn6qjqsmtepsegs23yyntnsy7qrvea"
  }
  vcn_id = oci_core_vcn.export_oke-vcn-quick-cluster1-cfcc03f15.id
}

resource oci_core_subnet export_oke-nodesubnet-quick-cluster1-cfcc03f15-regional {
  #availability_domain = <<Optional value not found in discovery>>
  cidr_block     = "10.0.10.0/24"
  compartment_id = var.compartment_ocid
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "oracleidentitycloudservice/mika.rinne@oracle.com"
    "Oracle-Tags.CreatedOn" = "2021-04-16T08:05:17.166Z"
  }
  dhcp_options_id = oci_core_vcn.export_oke-vcn-quick-cluster1-cfcc03f15.default_dhcp_options_id
  display_name    = "oke-nodesubnet-quick-cluster1-cfcc03f15-regional"
  dns_label       = "sub16535aac4"
  freeform_tags = {
  }
  #ipv6cidr_block = <<Optional value not found in discovery>>
  prohibit_internet_ingress  = "true"
  prohibit_public_ip_on_vnic = "true"
  route_table_id             = oci_core_route_table.export_oke-private-routetable-cluster1-cfcc03f15.id
  security_list_ids = [
    oci_core_security_list.export_oke-nodeseclist-quick-cluster1-cfcc03f15.id,
  ]
  vcn_id = oci_core_vcn.export_oke-vcn-quick-cluster1-cfcc03f15.id
}

resource oci_core_subnet export_oke-svclbsubnet-quick-cluster1-cfcc03f15-regional {
  #availability_domain = <<Optional value not found in discovery>>
  cidr_block     = "10.0.20.0/24"
  compartment_id = var.compartment_ocid
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "oracleidentitycloudservice/mika.rinne@oracle.com"
    "Oracle-Tags.CreatedOn" = "2021-04-16T08:05:16.789Z"
  }
  dhcp_options_id = oci_core_vcn.export_oke-vcn-quick-cluster1-cfcc03f15.default_dhcp_options_id
  display_name    = "oke-svclbsubnet-quick-cluster1-cfcc03f15-regional"
  dns_label       = "lbsubab35d6039"
  freeform_tags = {
  }
  #ipv6cidr_block = <<Optional value not found in discovery>>
  prohibit_internet_ingress  = "false"
  prohibit_public_ip_on_vnic = "false"
  route_table_id             = oci_core_vcn.export_oke-vcn-quick-cluster1-cfcc03f15.default_route_table_id
  security_list_ids = [
    oci_core_vcn.export_oke-vcn-quick-cluster1-cfcc03f15.default_security_list_id,
  ]
  vcn_id = oci_core_vcn.export_oke-vcn-quick-cluster1-cfcc03f15.id
}

resource oci_core_subnet export_oke-k8sendpoint-subnet-quick-cluster1-cfcc03f15-regional {
  #availability_domain = <<Optional value not found in discovery>>
  cidr_block     = "10.0.0.0/28"
  compartment_id = var.compartment_ocid
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "oracleidentitycloudservice/mika.rinne@oracle.com"
    "Oracle-Tags.CreatedOn" = "2021-04-16T08:05:16.355Z"
  }
  dhcp_options_id = oci_core_vcn.export_oke-vcn-quick-cluster1-cfcc03f15.default_dhcp_options_id
  display_name    = "oke-k8sendpoint-subnet-quick-cluster1-cfcc03f15-regional"
  dns_label       = "subd553a3f60"
  freeform_tags = {
  }
  #ipv6cidr_block = <<Optional value not found in discovery>>
  prohibit_internet_ingress  = "false"
  prohibit_public_ip_on_vnic = "false"
  route_table_id             = oci_core_vcn.export_oke-vcn-quick-cluster1-cfcc03f15.default_route_table_id
  security_list_ids = [
    oci_core_security_list.export_oke-k8sApiEndpoint-quick-cluster1-cfcc03f15.id,
  ]
  vcn_id = oci_core_vcn.export_oke-vcn-quick-cluster1-cfcc03f15.id
}

resource oci_core_private_ip export_Service-VNIC-for-cluster-ocid1-cluster-oc1-eu-frankfurt-1-aaaaaaaaei3jyn3j7tdszrqul2uevgiq4l46tm7wulzejkc37cuuo76edvoa {
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "oracleidentitycloudservice/mika.rinne@oracle.com"
    "Oracle-Tags.CreatedOn" = "2021-04-16T08:05:28.121Z"
  }
  display_name = "Service VNIC for cluster ocid1.cluster.oc1.eu-frankfurt-1.aaaaaaaaei3jyn3j7tdszrqul2uevgiq4l46tm7wulzejkc37cuuo76edvoa"
  freeform_tags = {
  }
  hostname_label = "host-10-0-0-13"
  ip_address     = "10.0.0.13"
  #vlan_id = <<Optional value not found in discovery>>
  vnic_id = "ocid1.vnic.oc1.eu-frankfurt-1.abtheljtqwdooa527st3tnwte2ui5dqx6o5k2o232de5rwx6r7teivyvc7oq"
}

resource oci_core_vcn export_oke-vcn-quick-cluster1-cfcc03f15 {
  #cidr_block = <<Optional value not found in discovery>>
  cidr_blocks = [
    "10.0.0.0/16",
  ]
  compartment_id = var.compartment_ocid
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "oracleidentitycloudservice/mika.rinne@oracle.com"
    "Oracle-Tags.CreatedOn" = "2021-04-16T08:05:10.322Z"
  }
  display_name = "oke-vcn-quick-cluster1-cfcc03f15"
  dns_label    = "cluster1"
  freeform_tags = {
  }
  #is_ipv6enabled = <<Optional value not found in discovery>>
}

resource oci_core_default_dhcp_options export_Default-DHCP-Options-for-oke-vcn-quick-cluster1-cfcc03f15 {
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "oracleidentitycloudservice/mika.rinne@oracle.com"
    "Oracle-Tags.CreatedOn" = "2021-04-16T08:05:10.322Z"
  }
  display_name = "Default DHCP Options for oke-vcn-quick-cluster1-cfcc03f15"
  freeform_tags = {
  }
  manage_default_resource_id = oci_core_vcn.export_oke-vcn-quick-cluster1-cfcc03f15.default_dhcp_options_id
  options {
    custom_dns_servers = [
    ]
    #search_domain_names = <<Optional value not found in discovery>>
    server_type = "VcnLocalPlusInternet"
    type        = "DomainNameServer"
  }
  options {
    #custom_dns_servers = <<Optional value not found in discovery>>
    search_domain_names = [
      "cluster1.oraclevcn.com",
    ]
    #server_type = <<Optional value not found in discovery>>
    type = "SearchDomain"
  }
}

resource oci_core_nat_gateway export_oke-ngw-quick-cluster1-cfcc03f15 {
  block_traffic  = "false"
  compartment_id = var.compartment_ocid
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "oracleidentitycloudservice/mika.rinne@oracle.com"
    "Oracle-Tags.CreatedOn" = "2021-04-16T08:05:11.192Z"
  }
  display_name = "oke-ngw-quick-cluster1-cfcc03f15"
  freeform_tags = {
  }
  public_ip_id = "ocid1.publicip.oc1.eu-frankfurt-1.aaaaaaaamn6lmshue33wmdch3nyiup7cufivdfwmbyeyliva6q4pjghntmha"
  vcn_id       = oci_core_vcn.export_oke-vcn-quick-cluster1-cfcc03f15.id
}

resource oci_core_route_table export_oke-private-routetable-cluster1-cfcc03f15 {
  compartment_id = var.compartment_ocid
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "oracleidentitycloudservice/mika.rinne@oracle.com"
    "Oracle-Tags.CreatedOn" = "2021-04-16T08:05:14.610Z"
  }
  display_name = "oke-private-routetable-cluster1-cfcc03f15"
  freeform_tags = {
  }
  route_rules {
    description       = "traffic to the internet"
    destination       = "0.0.0.0/0"
    destination_type  = "CIDR_BLOCK"
    network_entity_id = oci_core_nat_gateway.export_oke-ngw-quick-cluster1-cfcc03f15.id
  }
  route_rules {
    description       = "traffic to OCI services"
    destination       = "all-fra-services-in-oracle-services-network"
    destination_type  = "SERVICE_CIDR_BLOCK"
    network_entity_id = oci_core_service_gateway.export_oke-igw-quick-cluster1-cfcc03f15_1.id
  }
  vcn_id = oci_core_vcn.export_oke-vcn-quick-cluster1-cfcc03f15.id
}

resource oci_core_default_route_table export_oke-public-routetable-cluster1-cfcc03f15 {
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "oracleidentitycloudservice/mika.rinne@oracle.com"
    "Oracle-Tags.CreatedOn" = "2021-04-16T08:05:10.322Z"
  }
  display_name = "oke-public-routetable-cluster1-cfcc03f15"
  freeform_tags = {
  }
  manage_default_resource_id = oci_core_vcn.export_oke-vcn-quick-cluster1-cfcc03f15.default_route_table_id
  route_rules {
    description       = "traffic to/from internet"
    destination       = "0.0.0.0/0"
    destination_type  = "CIDR_BLOCK"
    network_entity_id = oci_core_internet_gateway.export_oke-igw-quick-cluster1-cfcc03f15.id
  }
}

resource oci_core_security_list export_oke-nodeseclist-quick-cluster1-cfcc03f15 {
  compartment_id = var.compartment_ocid
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "oracleidentitycloudservice/mika.rinne@oracle.com"
    "Oracle-Tags.CreatedOn" = "2021-04-16T08:05:15.932Z"
  }
  display_name = "oke-nodeseclist-quick-cluster1-cfcc03f15"
  egress_security_rules {
    description      = "Allow pods on one worker node to communicate with pods on other worker nodes"
    destination      = "10.0.10.0/24"
    destination_type = "CIDR_BLOCK"
    #icmp_options = <<Optional value not found in discovery>>
    protocol  = "all"
    stateless = "false"
    #tcp_options = <<Optional value not found in discovery>>
    #udp_options = <<Optional value not found in discovery>>
  }
  egress_security_rules {
    description      = "Access to Kubernetes API Endpoint"
    destination      = "10.0.0.0/28"
    destination_type = "CIDR_BLOCK"
    #icmp_options = <<Optional value not found in discovery>>
    protocol  = "6"
    stateless = "false"
    tcp_options {
      max = "6443"
      min = "6443"
      #source_port_range = <<Optional value not found in discovery>>
    }
    #udp_options = <<Optional value not found in discovery>>
  }
  egress_security_rules {
    description      = "Kubernetes worker to control plane communication"
    destination      = "10.0.0.0/28"
    destination_type = "CIDR_BLOCK"
    #icmp_options = <<Optional value not found in discovery>>
    protocol  = "6"
    stateless = "false"
    tcp_options {
      max = "12250"
      min = "12250"
      #source_port_range = <<Optional value not found in discovery>>
    }
    #udp_options = <<Optional value not found in discovery>>
  }
  egress_security_rules {
    description      = "Path discovery"
    destination      = "10.0.0.0/28"
    destination_type = "CIDR_BLOCK"
    icmp_options {
      code = "4"
      type = "3"
    }
    protocol  = "1"
    stateless = "false"
    #tcp_options = <<Optional value not found in discovery>>
    #udp_options = <<Optional value not found in discovery>>
  }
  egress_security_rules {
    description      = "Allow nodes to communicate with OKE to ensure correct start-up and continued functioning"
    destination      = "all-fra-services-in-oracle-services-network"
    destination_type = "SERVICE_CIDR_BLOCK"
    #icmp_options = <<Optional value not found in discovery>>
    protocol  = "6"
    stateless = "false"
    tcp_options {
      max = "443"
      min = "443"
      #source_port_range = <<Optional value not found in discovery>>
    }
    #udp_options = <<Optional value not found in discovery>>
  }
  egress_security_rules {
    description      = "ICMP Access from Kubernetes Control Plane"
    destination      = "0.0.0.0/0"
    destination_type = "CIDR_BLOCK"
    icmp_options {
      code = "4"
      type = "3"
    }
    protocol  = "1"
    stateless = "false"
    #tcp_options = <<Optional value not found in discovery>>
    #udp_options = <<Optional value not found in discovery>>
  }
  egress_security_rules {
    description      = "Worker Nodes access to Internet"
    destination      = "0.0.0.0/0"
    destination_type = "CIDR_BLOCK"
    #icmp_options = <<Optional value not found in discovery>>
    protocol  = "all"
    stateless = "false"
    #tcp_options = <<Optional value not found in discovery>>
    #udp_options = <<Optional value not found in discovery>>
  }
  freeform_tags = {
  }
  ingress_security_rules {
    description = "Allow pods on one worker node to communicate with pods on other worker nodes"
    #icmp_options = <<Optional value not found in discovery>>
    protocol    = "all"
    source      = "10.0.10.0/24"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    #tcp_options = <<Optional value not found in discovery>>
    #udp_options = <<Optional value not found in discovery>>
  }
  ingress_security_rules {
    description = "Path discovery"
    icmp_options {
      code = "4"
      type = "3"
    }
    protocol    = "1"
    source      = "10.0.0.0/28"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    #tcp_options = <<Optional value not found in discovery>>
    #udp_options = <<Optional value not found in discovery>>
  }
  ingress_security_rules {
    description = "TCP access from Kubernetes Control Plane"
    #icmp_options = <<Optional value not found in discovery>>
    protocol    = "6"
    source      = "10.0.0.0/28"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    #tcp_options = <<Optional value not found in discovery>>
    #udp_options = <<Optional value not found in discovery>>
  }
  ingress_security_rules {
    description = "Inbound SSH traffic to worker nodes"
    #icmp_options = <<Optional value not found in discovery>>
    protocol    = "6"
    source      = "0.0.0.0/0"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    tcp_options {
      max = "22"
      min = "22"
      #source_port_range = <<Optional value not found in discovery>>
    }
    #udp_options = <<Optional value not found in discovery>>
  }
  vcn_id = oci_core_vcn.export_oke-vcn-quick-cluster1-cfcc03f15.id
}

resource oci_core_security_list export_oke-k8sApiEndpoint-quick-cluster1-cfcc03f15 {
  compartment_id = var.compartment_ocid
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "oracleidentitycloudservice/mika.rinne@oracle.com"
    "Oracle-Tags.CreatedOn" = "2021-04-16T08:05:15.031Z"
  }
  display_name = "oke-k8sApiEndpoint-quick-cluster1-cfcc03f15"
  egress_security_rules {
    description      = "Allow Kubernetes Control Plane to communicate with OKE"
    destination      = "all-fra-services-in-oracle-services-network"
    destination_type = "SERVICE_CIDR_BLOCK"
    #icmp_options = <<Optional value not found in discovery>>
    protocol  = "6"
    stateless = "false"
    tcp_options {
      max = "443"
      min = "443"
      #source_port_range = <<Optional value not found in discovery>>
    }
    #udp_options = <<Optional value not found in discovery>>
  }
  egress_security_rules {
    description      = "All traffic to worker nodes"
    destination      = "10.0.10.0/24"
    destination_type = "CIDR_BLOCK"
    #icmp_options = <<Optional value not found in discovery>>
    protocol  = "6"
    stateless = "false"
    #tcp_options = <<Optional value not found in discovery>>
    #udp_options = <<Optional value not found in discovery>>
  }
  egress_security_rules {
    description      = "Path discovery"
    destination      = "10.0.10.0/24"
    destination_type = "CIDR_BLOCK"
    icmp_options {
      code = "4"
      type = "3"
    }
    protocol  = "1"
    stateless = "false"
    #tcp_options = <<Optional value not found in discovery>>
    #udp_options = <<Optional value not found in discovery>>
  }
  freeform_tags = {
  }
  ingress_security_rules {
    description = "External access to Kubernetes API endpoint"
    #icmp_options = <<Optional value not found in discovery>>
    protocol    = "6"
    source      = "0.0.0.0/0"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    tcp_options {
      max = "6443"
      min = "6443"
      #source_port_range = <<Optional value not found in discovery>>
    }
    #udp_options = <<Optional value not found in discovery>>
  }
  ingress_security_rules {
    description = "Kubernetes worker to Kubernetes API endpoint communication"
    #icmp_options = <<Optional value not found in discovery>>
    protocol    = "6"
    source      = "10.0.10.0/24"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    tcp_options {
      max = "6443"
      min = "6443"
      #source_port_range = <<Optional value not found in discovery>>
    }
    #udp_options = <<Optional value not found in discovery>>
  }
  ingress_security_rules {
    description = "Kubernetes worker to control plane communication"
    #icmp_options = <<Optional value not found in discovery>>
    protocol    = "6"
    source      = "10.0.10.0/24"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    tcp_options {
      max = "12250"
      min = "12250"
      #source_port_range = <<Optional value not found in discovery>>
    }
    #udp_options = <<Optional value not found in discovery>>
  }
  ingress_security_rules {
    description = "Path discovery"
    icmp_options {
      code = "4"
      type = "3"
    }
    protocol    = "1"
    source      = "10.0.10.0/24"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    #tcp_options = <<Optional value not found in discovery>>
    #udp_options = <<Optional value not found in discovery>>
  }
  vcn_id = oci_core_vcn.export_oke-vcn-quick-cluster1-cfcc03f15.id
}

resource oci_core_default_security_list export_oke-svclbseclist-quick-cluster1-cfcc03f15 {
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "oracleidentitycloudservice/mika.rinne@oracle.com"
    "Oracle-Tags.CreatedOn" = "2021-04-16T08:05:10.322Z"
  }
  display_name = "oke-svclbseclist-quick-cluster1-cfcc03f15"
  freeform_tags = {
  }
  manage_default_resource_id = oci_core_vcn.export_oke-vcn-quick-cluster1-cfcc03f15.default_security_list_id
}

